import z from 'zod';

export const ReleasesList = z.array(
  z.object({
    url: z.string(),
    html_url: z.string(),
    assets_url: z.string(),
    upload_url: z.string(),
    tarball_url: z.string(),
    zipball_url: z.string(),
    discussion_url: z.string().optional(),
    id: z.int().positive(),
    node_id: z.string(),
    tag_name: z.string(),
    target_commitish: z.string(),
    name: z.string(),
    body: z.string(),
    draft: z.boolean(),
    prerelease: z.boolean(),
    immutable: z.boolean(),
    created_at: z.iso.datetime(),
    published_at: z.iso.datetime(),
    author: z.object({
      login: z.string(),
      id: z.int().positive(),
      node_id: z.string(),
      avatar_url: z.string(),
      gravatar_id: z.string(),
      url: z.string(),
      html_url: z.string(),
      followers_url: z.string(),
      following_url: z.string(),
      gists_url: z.string(),
      starred_url: z.string(),
      subscriptions_url: z.string(),
      organizations_url: z.string(),
      repos_url: z.string(),
      events_url: z.string(),
      received_events_url: z.string(),
      type: z.string(),
      site_admin: z.boolean(),
    }),
    assets: z.array(
      z.object({
        url: z.string(),
        browser_download_url: z.string(),
        id: z.int().positive(),
        node_id: z.string(),
        name: z.string(),
        label: z.string().nullable(),
        state: z.string(),
        content_type: z.string(),
        size: z.int().positive(),
        digest: z.string().nullable(),
        download_count: z.int(),
        created_at: z.iso.datetime(),
        updated_at: z.iso.datetime(),
        uploader: z.object({
          login: z.string(),
          id: z.int().positive(),
          node_id: z.string(),
          avatar_url: z.string(),
          gravatar_id: z.string(),
          url: z.string(),
          html_url: z.string(),
          followers_url: z.string(),
          following_url: z.string(),
          gists_url: z.string(),
          starred_url: z.string(),
          subscriptions_url: z.string(),
          organizations_url: z.string(),
          repos_url: z.string(),
          events_url: z.string(),
          received_events_url: z.string(),
          type: z.string(),
          site_admin: z.boolean(),
        }),
      }),
    ),
  }),
);

export type ReleasesListT = z.infer<typeof ReleasesList>;
